spring.application.name=youngsters-sports-club
server.port=${PORT:8080}
spring.web.resources.static-locations=classpath:/static/

logging.level.root=INFO
logging.level.com.youngstersclub=INFO
logging.level.org.springframework.web=INFO
